### ISSUE TITLE
 IndexError: index 2048 is out of bounds for axis 1 with size 2

### ISSUE THREAD

**Issue by shaheer2019** [aaravindravi/A-Dataset-and-Preliminary-Results-for-Umpire-Pose-Detection-Using-SVM-Classification-of-Deep-Feature#3]
#Storing the extracted features
X=[]
X1 = np.load('class_1data_model1.npy')
X2 = np.load('class_2data_model1.npy')
X_data = np.append(X1,X2,axis=0)
Y_data = X_data[:,2048]
X_data = X_data[:,0:2048]
x_tr,x_ts,y_tr,y_ts = train_test_split(X_data, Y_data, test_size=0.2,random_state=10)
-------this chunk of coode this from classifer-model file.----
IndexError                                Traceback (most recent call last)
<ipython-input-6-fdc15cf591ed> in <module>()
     39 X2 = np.load('class_2data_model1.npy')
     40 X_data = np.append(X1,X2,axis=0)
---> 41 Y_data = X_data[:,2048]
     42 X_data = X_data[:,0:2048]
     43 x_tr,x_ts,y_tr,y_ts = train_test_split(X_data, Y_data, test_size=0.2,random_state=10)

IndexError: index 2048 is out of bounds for axis 1 with size 2

**Comment by Shanzaay** [comment]
Hi. Have you been able to resolve the issue? If you did can you please share the solution with me.

**Comment by aaravindravi** [comment]
Hello Shaheer,
Could you please provide the filename and the steps followed prior to running this file. I would be able to look into the issue and get back to you. I will also try to update the steps to run the scripts. 

I had also addressed this in an earlier issue for this repo, which I have re-opened, were you able to try any of the suggestions listed there?

**Comment by aaravindravi** [comment]
Hello Shanzaay, thank you letting me know that you are facing a similar issue. I will look into the files and errors, and provide the updated versions.

**Comment by aaravindravi** [comment]
Hello Shahreer and Shanzaay,
I have updated the code and all the README files for all folders. Please ensure that you have copied the datasets of each class into the respective folders with the class name as the folder name (more info. in the readme files). This error shold not occur if the numpy files (features) have been generated correctly. I have re-written the code to directly read from the second dimension instead of explicitly writing 2048 for the Inception V3 features. Hope you don't face this issue again.
The key part here is to ensure that you have generated the features for each class and to do this the files have to be places in the respective folders (to use this code as is). Otherwise, you can directly call the files by their class names (you will have to slightly modify this code for that).

Please try them out and let me know if you still face any issues.

**Comment by Shanzaay** [comment]
Thanks a bunch Aravind...
